<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QuickCalc.Core\QuickCalc.Core.csproj" />
    <ProjectReference Include="..\QuickCalc.Windows\QuickCalc.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>QuickCalc.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Update="hotkeys.json"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></None>
    <EmbeddedResource Include="QuickCalc.ico" LogicalName="QuickCalc.App.QuickCalc.ico" />
  </ItemGroup>

</Project>
